/**
 * Zod schemas for /v1/projects/<ref>/config/auth.
 *
 * Mirrors the full upstream shape: components.schemas.UpdateAuthConfigBody
 * from specs/009-runtime-config-tunables/upstream-openapi-snapshot.json.
 * 234 fields. Bounds match the snapshot exactly.
 *
 * This file is generated from the OpenAPI snapshot — see jq pipeline in
 * specs/009-runtime-config-tunables/quickstart.md. The contract test in
 * apps/api/tests/unit/mgmt-api-config-validation.test.ts re-derives bounds
 * from the snapshot and asserts equality with this schema; upstream drift
 * is caught there, not silently.
 *
 * Spec: specs/009-runtime-config-tunables/spec.md FR-003..FR-005.
 * Contract: specs/009-runtime-config-tunables/contracts/auth-config.md
 */
import { z } from 'zod';

/** Redaction sentinel returned in place of plaintext secrets on GET. */
export const REDACTED_SECRET = '***';

/**
 * Field names whose values MUST be redacted on GET and which honor the
 * "***" sentinel as "leave existing value unchanged" on PATCH.
 * Pattern: name ends in _secret, _secrets, _pass, _api_key, _api_secret,
 * or _access_key — see Q5 in spec Clarifications.
 */
export const SECRET_FIELDS: ReadonlySet<string> = new Set<string>([
  "smtp_pass",
  "security_captcha_secret",
  "sms_messagebird_access_key",
  "sms_textlocal_api_key",
  "sms_vonage_api_key",
  "sms_vonage_api_secret",
  "hook_mfa_verification_attempt_secrets",
  "hook_password_verification_attempt_secrets",
  "hook_custom_access_token_secrets",
  "hook_send_sms_secrets",
  "hook_send_email_secrets",
  "hook_before_user_created_secrets",
  "hook_after_user_created_secrets",
  "external_apple_secret",
  "external_azure_secret",
  "external_bitbucket_secret",
  "external_discord_secret",
  "external_facebook_secret",
  "external_figma_secret",
  "external_github_secret",
  "external_gitlab_secret",
  "external_google_secret",
  "external_kakao_secret",
  "external_keycloak_secret",
  "external_linkedin_oidc_secret",
  "external_slack_oidc_secret",
  "external_notion_secret",
  "external_slack_secret",
  "external_spotify_secret",
  "external_twitch_secret",
  "external_twitter_secret",
  "external_x_secret",
  "external_workos_secret",
  "external_zoom_secret",
  "nimbus_oauth_client_secret",
]);

// ─── PATCH request body — full upstream UpdateAuthConfigBody shape ─────────
//
// .strict() so unknown fields → ZodError → 400 unknown_field per FR-005.
// All fields are .optional() (PATCH is merge-over-existing) and .nullable()
// because upstream marks every property nullable.
export const UpdateAuthConfigBodySchema = z
  .object({
    site_url: z.string().nullable().optional(),
    disable_signup: z.boolean().nullable().optional(),
    jwt_exp: z.number().int().min(0).max(604800).nullable().optional(),
    smtp_admin_email: z.string().nullable().optional(),
    smtp_host: z.string().nullable().optional(),
    smtp_port: z.string().nullable().optional(),
    smtp_user: z.string().nullable().optional(),
    smtp_pass: z.string().nullable().optional(),
    smtp_max_frequency: z.number().int().min(0).max(32767).nullable().optional(),
    smtp_sender_name: z.string().nullable().optional(),
    mailer_allow_unverified_email_sign_ins: z.boolean().nullable().optional(),
    mailer_autoconfirm: z.boolean().nullable().optional(),
    mailer_subjects_invite: z.string().nullable().optional(),
    mailer_subjects_confirmation: z.string().nullable().optional(),
    mailer_subjects_recovery: z.string().nullable().optional(),
    mailer_subjects_email_change: z.string().nullable().optional(),
    mailer_subjects_magic_link: z.string().nullable().optional(),
    mailer_subjects_reauthentication: z.string().nullable().optional(),
    mailer_subjects_password_changed_notification: z.string().nullable().optional(),
    mailer_subjects_email_changed_notification: z.string().nullable().optional(),
    mailer_subjects_phone_changed_notification: z.string().nullable().optional(),
    mailer_subjects_mfa_factor_enrolled_notification: z.string().nullable().optional(),
    mailer_subjects_mfa_factor_unenrolled_notification: z.string().nullable().optional(),
    mailer_subjects_identity_linked_notification: z.string().nullable().optional(),
    mailer_subjects_identity_unlinked_notification: z.string().nullable().optional(),
    mailer_templates_invite_content: z.string().nullable().optional(),
    mailer_templates_confirmation_content: z.string().nullable().optional(),
    mailer_templates_recovery_content: z.string().nullable().optional(),
    mailer_templates_email_change_content: z.string().nullable().optional(),
    mailer_templates_magic_link_content: z.string().nullable().optional(),
    mailer_templates_reauthentication_content: z.string().nullable().optional(),
    mailer_templates_password_changed_notification_content: z.string().nullable().optional(),
    mailer_templates_email_changed_notification_content: z.string().nullable().optional(),
    mailer_templates_phone_changed_notification_content: z.string().nullable().optional(),
    mailer_templates_mfa_factor_enrolled_notification_content: z.string().nullable().optional(),
    mailer_templates_mfa_factor_unenrolled_notification_content: z.string().nullable().optional(),
    mailer_templates_identity_linked_notification_content: z.string().nullable().optional(),
    mailer_templates_identity_unlinked_notification_content: z.string().nullable().optional(),
    mailer_notifications_password_changed_enabled: z.boolean().nullable().optional(),
    mailer_notifications_email_changed_enabled: z.boolean().nullable().optional(),
    mailer_notifications_phone_changed_enabled: z.boolean().nullable().optional(),
    mailer_notifications_mfa_factor_enrolled_enabled: z.boolean().nullable().optional(),
    mailer_notifications_mfa_factor_unenrolled_enabled: z.boolean().nullable().optional(),
    mailer_notifications_identity_linked_enabled: z.boolean().nullable().optional(),
    mailer_notifications_identity_unlinked_enabled: z.boolean().nullable().optional(),
    mfa_max_enrolled_factors: z.number().int().min(0).max(2147483647).nullable().optional(),
    uri_allow_list: z.string().nullable().optional(),
    external_anonymous_users_enabled: z.boolean().nullable().optional(),
    external_email_enabled: z.boolean().nullable().optional(),
    external_phone_enabled: z.boolean().nullable().optional(),
    saml_enabled: z.boolean().nullable().optional(),
    saml_external_url: z.string().nullable().optional(),
    security_sb_forwarded_for_enabled: z.boolean().nullable().optional(),
    security_captcha_enabled: z.boolean().nullable().optional(),
    security_captcha_provider: z.enum(["turnstile", "hcaptcha"] as const).nullable().optional(),
    security_captcha_secret: z.string().nullable().optional(),
    sessions_timebox: z.number().min(0).nullable().optional(),
    sessions_inactivity_timeout: z.number().min(0).nullable().optional(),
    sessions_single_per_user: z.boolean().nullable().optional(),
    sessions_tags: z.string().nullable().optional(),
    rate_limit_anonymous_users: z.number().int().min(1).max(2147483647).nullable().optional(),
    rate_limit_email_sent: z.number().int().min(1).max(2147483647).nullable().optional(),
    rate_limit_sms_sent: z.number().int().min(1).max(2147483647).nullable().optional(),
    rate_limit_verify: z.number().int().min(1).max(2147483647).nullable().optional(),
    rate_limit_token_refresh: z.number().int().min(1).max(2147483647).nullable().optional(),
    rate_limit_otp: z.number().int().min(1).max(2147483647).nullable().optional(),
    rate_limit_web3: z.number().int().min(1).max(2147483647).nullable().optional(),
    mailer_secure_email_change_enabled: z.boolean().nullable().optional(),
    refresh_token_rotation_enabled: z.boolean().nullable().optional(),
    password_hibp_enabled: z.boolean().nullable().optional(),
    password_min_length: z.number().int().min(6).max(32767).nullable().optional(),
    password_required_characters: z.enum(["abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789", "abcdefghijklmnopqrstuvwxyz:ABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789", "abcdefghijklmnopqrstuvwxyz:ABCDEFGHIJKLMNOPQRSTUVWXYZ:0123456789:!@#$%^&*()_+-=[]{};'\\\\:\"|<>?,./`~", ""] as const).nullable().optional(),
    security_manual_linking_enabled: z.boolean().nullable().optional(),
    security_update_password_require_reauthentication: z.boolean().nullable().optional(),
    security_refresh_token_reuse_interval: z.number().int().min(0).max(2147483647).nullable().optional(),
    mailer_otp_exp: z.number().int().min(0).max(2147483647).nullable().optional(),
    mailer_otp_length: z.number().int().min(6).max(10).nullable().optional(),
    sms_autoconfirm: z.boolean().nullable().optional(),
    sms_max_frequency: z.number().int().min(0).max(32767).nullable().optional(),
    sms_otp_exp: z.number().int().min(0).max(2147483647).nullable().optional(),
    sms_otp_length: z.number().int().min(0).max(32767).nullable().optional(),
    sms_provider: z.enum(["messagebird", "textlocal", "twilio", "twilio_verify", "vonage"] as const).nullable().optional(),
    sms_messagebird_access_key: z.string().nullable().optional(),
    sms_messagebird_originator: z.string().nullable().optional(),
    sms_test_otp: z.string().nullable().optional(),
    sms_test_otp_valid_until: z.string().nullable().optional(),
    sms_textlocal_api_key: z.string().nullable().optional(),
    sms_textlocal_sender: z.string().nullable().optional(),
    sms_twilio_account_sid: z.string().nullable().optional(),
    sms_twilio_auth_token: z.string().nullable().optional(),
    sms_twilio_content_sid: z.string().nullable().optional(),
    sms_twilio_message_service_sid: z.string().nullable().optional(),
    sms_twilio_verify_account_sid: z.string().nullable().optional(),
    sms_twilio_verify_auth_token: z.string().nullable().optional(),
    sms_twilio_verify_message_service_sid: z.string().nullable().optional(),
    sms_vonage_api_key: z.string().nullable().optional(),
    sms_vonage_api_secret: z.string().nullable().optional(),
    sms_vonage_from: z.string().nullable().optional(),
    sms_template: z.string().nullable().optional(),
    hook_mfa_verification_attempt_enabled: z.boolean().nullable().optional(),
    hook_mfa_verification_attempt_uri: z.string().nullable().optional(),
    hook_mfa_verification_attempt_secrets: z.string().nullable().optional(),
    hook_password_verification_attempt_enabled: z.boolean().nullable().optional(),
    hook_password_verification_attempt_uri: z.string().nullable().optional(),
    hook_password_verification_attempt_secrets: z.string().nullable().optional(),
    hook_custom_access_token_enabled: z.boolean().nullable().optional(),
    hook_custom_access_token_uri: z.string().nullable().optional(),
    hook_custom_access_token_secrets: z.string().nullable().optional(),
    hook_send_sms_enabled: z.boolean().nullable().optional(),
    hook_send_sms_uri: z.string().nullable().optional(),
    hook_send_sms_secrets: z.string().nullable().optional(),
    hook_send_email_enabled: z.boolean().nullable().optional(),
    hook_send_email_uri: z.string().nullable().optional(),
    hook_send_email_secrets: z.string().nullable().optional(),
    hook_before_user_created_enabled: z.boolean().nullable().optional(),
    hook_before_user_created_uri: z.string().nullable().optional(),
    hook_before_user_created_secrets: z.string().nullable().optional(),
    hook_after_user_created_enabled: z.boolean().nullable().optional(),
    hook_after_user_created_uri: z.string().nullable().optional(),
    hook_after_user_created_secrets: z.string().nullable().optional(),
    external_apple_enabled: z.boolean().nullable().optional(),
    external_apple_client_id: z.string().nullable().optional(),
    external_apple_email_optional: z.boolean().nullable().optional(),
    external_apple_secret: z.string().nullable().optional(),
    external_apple_additional_client_ids: z.string().nullable().optional(),
    external_azure_enabled: z.boolean().nullable().optional(),
    external_azure_client_id: z.string().nullable().optional(),
    external_azure_email_optional: z.boolean().nullable().optional(),
    external_azure_secret: z.string().nullable().optional(),
    external_azure_url: z.string().nullable().optional(),
    external_bitbucket_enabled: z.boolean().nullable().optional(),
    external_bitbucket_client_id: z.string().nullable().optional(),
    external_bitbucket_email_optional: z.boolean().nullable().optional(),
    external_bitbucket_secret: z.string().nullable().optional(),
    external_discord_enabled: z.boolean().nullable().optional(),
    external_discord_client_id: z.string().nullable().optional(),
    external_discord_email_optional: z.boolean().nullable().optional(),
    external_discord_secret: z.string().nullable().optional(),
    external_facebook_enabled: z.boolean().nullable().optional(),
    external_facebook_client_id: z.string().nullable().optional(),
    external_facebook_email_optional: z.boolean().nullable().optional(),
    external_facebook_secret: z.string().nullable().optional(),
    external_figma_enabled: z.boolean().nullable().optional(),
    external_figma_client_id: z.string().nullable().optional(),
    external_figma_email_optional: z.boolean().nullable().optional(),
    external_figma_secret: z.string().nullable().optional(),
    external_github_enabled: z.boolean().nullable().optional(),
    external_github_client_id: z.string().nullable().optional(),
    external_github_email_optional: z.boolean().nullable().optional(),
    external_github_secret: z.string().nullable().optional(),
    external_gitlab_enabled: z.boolean().nullable().optional(),
    external_gitlab_client_id: z.string().nullable().optional(),
    external_gitlab_email_optional: z.boolean().nullable().optional(),
    external_gitlab_secret: z.string().nullable().optional(),
    external_gitlab_url: z.string().nullable().optional(),
    external_google_enabled: z.boolean().nullable().optional(),
    external_google_client_id: z.string().nullable().optional(),
    external_google_email_optional: z.boolean().nullable().optional(),
    external_google_secret: z.string().nullable().optional(),
    external_google_additional_client_ids: z.string().nullable().optional(),
    external_google_skip_nonce_check: z.boolean().nullable().optional(),
    external_kakao_enabled: z.boolean().nullable().optional(),
    external_kakao_client_id: z.string().nullable().optional(),
    external_kakao_email_optional: z.boolean().nullable().optional(),
    external_kakao_secret: z.string().nullable().optional(),
    external_keycloak_enabled: z.boolean().nullable().optional(),
    external_keycloak_client_id: z.string().nullable().optional(),
    external_keycloak_email_optional: z.boolean().nullable().optional(),
    external_keycloak_secret: z.string().nullable().optional(),
    external_keycloak_url: z.string().nullable().optional(),
    external_linkedin_oidc_enabled: z.boolean().nullable().optional(),
    external_linkedin_oidc_client_id: z.string().nullable().optional(),
    external_linkedin_oidc_email_optional: z.boolean().nullable().optional(),
    external_linkedin_oidc_secret: z.string().nullable().optional(),
    external_slack_oidc_enabled: z.boolean().nullable().optional(),
    external_slack_oidc_client_id: z.string().nullable().optional(),
    external_slack_oidc_email_optional: z.boolean().nullable().optional(),
    external_slack_oidc_secret: z.string().nullable().optional(),
    external_notion_enabled: z.boolean().nullable().optional(),
    external_notion_client_id: z.string().nullable().optional(),
    external_notion_email_optional: z.boolean().nullable().optional(),
    external_notion_secret: z.string().nullable().optional(),
    external_slack_enabled: z.boolean().nullable().optional(),
    external_slack_client_id: z.string().nullable().optional(),
    external_slack_email_optional: z.boolean().nullable().optional(),
    external_slack_secret: z.string().nullable().optional(),
    external_spotify_enabled: z.boolean().nullable().optional(),
    external_spotify_client_id: z.string().nullable().optional(),
    external_spotify_email_optional: z.boolean().nullable().optional(),
    external_spotify_secret: z.string().nullable().optional(),
    external_twitch_enabled: z.boolean().nullable().optional(),
    external_twitch_client_id: z.string().nullable().optional(),
    external_twitch_email_optional: z.boolean().nullable().optional(),
    external_twitch_secret: z.string().nullable().optional(),
    external_twitter_enabled: z.boolean().nullable().optional(),
    external_twitter_client_id: z.string().nullable().optional(),
    external_twitter_email_optional: z.boolean().nullable().optional(),
    external_twitter_secret: z.string().nullable().optional(),
    external_x_enabled: z.boolean().nullable().optional(),
    external_x_client_id: z.string().nullable().optional(),
    external_x_email_optional: z.boolean().nullable().optional(),
    external_x_secret: z.string().nullable().optional(),
    external_workos_enabled: z.boolean().nullable().optional(),
    external_workos_client_id: z.string().nullable().optional(),
    external_workos_secret: z.string().nullable().optional(),
    external_workos_url: z.string().nullable().optional(),
    external_web3_solana_enabled: z.boolean().nullable().optional(),
    external_web3_ethereum_enabled: z.boolean().nullable().optional(),
    external_zoom_enabled: z.boolean().nullable().optional(),
    external_zoom_client_id: z.string().nullable().optional(),
    external_zoom_email_optional: z.boolean().nullable().optional(),
    external_zoom_secret: z.string().nullable().optional(),
    db_max_pool_size: z.number().int().nullable().optional(),
    db_max_pool_size_unit: z.enum(["connections", "percent"] as const).nullable().optional(),
    api_max_request_duration: z.number().int().nullable().optional(),
    mfa_totp_enroll_enabled: z.boolean().nullable().optional(),
    mfa_totp_verify_enabled: z.boolean().nullable().optional(),
    mfa_web_authn_enroll_enabled: z.boolean().nullable().optional(),
    mfa_web_authn_verify_enabled: z.boolean().nullable().optional(),
    passkey_enabled: z.boolean().nullable().optional(),
    webauthn_rp_display_name: z.string().nullable().optional(),
    webauthn_rp_id: z.string().nullable().optional(),
    webauthn_rp_origins: z.string().nullable().optional(),
    mfa_phone_enroll_enabled: z.boolean().nullable().optional(),
    mfa_phone_verify_enabled: z.boolean().nullable().optional(),
    mfa_phone_max_frequency: z.number().int().min(0).max(32767).nullable().optional(),
    mfa_phone_otp_length: z.number().int().min(0).max(32767).nullable().optional(),
    mfa_phone_template: z.string().nullable().optional(),
    nimbus_oauth_client_id: z.string().nullable().optional(),
    nimbus_oauth_client_secret: z.string().nullable().optional(),
    oauth_server_enabled: z.boolean().nullable().optional(),
    oauth_server_allow_dynamic_registration: z.boolean().nullable().optional(),
    oauth_server_authorization_path: z.string().nullable().optional(),
    custom_oauth_enabled: z.boolean().nullable().optional(),
  })
  .strict();

export type UpdateAuthConfigBody = z.infer<typeof UpdateAuthConfigBodySchema>;

// ─── GET / PATCH response — same shape as request, secrets redacted ────────
//
// Response uses the same shape; redaction of SECRET_FIELDS happens at the
// runtime-config-store boundary, not in the Zod schema.
export const AuthConfigResponseSchema = UpdateAuthConfigBodySchema;
export type AuthConfigResponse = z.infer<typeof AuthConfigResponseSchema>;

/** Field names enumerated for the field-mapper test (T021). */
export const ALL_AUTH_CONFIG_FIELDS: ReadonlyArray<string> = Object.keys(
  UpdateAuthConfigBodySchema.shape,
);
