import { describe, expect, it } from 'vitest';
import {
  generateServerKeypair,
  encryptForClient,
  encryptForClientWithFixedKey,
  generateDeviceCode,
  validateClientPublicKey,
} from '../../src/services/cli-login-crypto.js';
import { createECDH, createDecipheriv } from 'node:crypto';

/**
 * T005: cli-login-crypto unit tests.
 *
 * The known-vector test (Go interop) is the critical one — it proves our
 * AES-GCM auth-tag concatenation matches what Go's cipher.NewGCM(...).Seal
 * produces, which is what the upstream supabase CLI expects.
 *
 * Vectors generated by running tests/vectors/gen-cli-login-vectors.go
 * (committed to the repo for reproducibility — see tasks T005).
 */

// Vectors produced by /tmp/gen-cli-login-vectors.go on 2026-05-25 with go1.24.1.
const VECTOR = {
  serverPrivHex:
    '48dfb983722e59dddaa4f2c73dd0b0854ebab3d868426b1b5a62ea61a7dafd24',
  serverPubHex:
    '04ef3b0de478b72d105be50bba6612ea8bee84828f39f623a051024723882f12f8bcb5c878f43691c56053cc928312fd6e3b5e8b0ceb53e34d47198a2c242d6ab9',
  clientPrivHex:
    '75655d7b1596afac3bde6b9f00a31c60a809c032ee0a42040274d010c68f3218',
  clientPubHex:
    '047c1f0692dfd6206628f693b40f1ea4abfef4a258da44b818652650c1ae062f9a401a4bb5d47b10804f8ec103c35dd3af8693894c3fce3a44693d7d9d2637c352',
  sharedSecretHex:
    '170fea23ae2307e35c0189d10566eae5d0dcba7f6cf4fa4bd47dbce17eda4cbd',
  nonceHex: '70520d18784834b2723ca429',
  plaintext: 'sbp_0123456789abcdef0123456789abcdef01234567',
  ciphertextHex:
    'c431033930539d68d0f480ea121601f0d8087ff24170d7d44980c5b94c173493503ab49b57fa44cb0b259646ad9ef6a8f05ec6a0cf61cc5e242c3176',
};

describe('generateServerKeypair', () => {
  it('returns 32-byte private + 65-byte uncompressed public key (starts with 0x04)', () => {
    const kp = generateServerKeypair();
    expect(kp.privateKey.length).toBe(32);
    expect(kp.publicKey.length).toBe(65);
    expect(kp.publicKey[0]).toBe(0x04);
  });

  it('100 successive calls produce distinct private keys (sanity)', () => {
    const seen = new Set<string>();
    for (let i = 0; i < 100; i++) seen.add(generateServerKeypair().privateKey.toString('hex'));
    expect(seen.size).toBe(100);
  });
});

describe('encryptForClient — Go-interop known-vector (THE security-critical test)', () => {
  it('produces byte-identical ciphertext to Go cipher.Seal with same keys+nonce+plaintext', () => {
    const bundle = encryptForClientWithFixedKey(
      VECTOR.plaintext,
      VECTOR.clientPubHex,
      VECTOR.serverPrivHex,
      VECTOR.nonceHex,
    );
    expect(bundle.accessTokenHex).toBe(VECTOR.ciphertextHex);
    expect(bundle.publicKeyHex).toBe(VECTOR.serverPubHex);
    expect(bundle.nonceHex).toBe(VECTOR.nonceHex);
  });

  it('the bundle decrypts back to plaintext using the client private key (round-trip)', () => {
    const bundle = encryptForClientWithFixedKey(
      VECTOR.plaintext,
      VECTOR.clientPubHex,
      VECTOR.serverPrivHex,
      VECTOR.nonceHex,
    );

    // Reproduce what the CLI does: ECDH(client_priv, server_pub) then AES-GCM Open.
    const cliEcdh = createECDH('prime256v1');
    cliEcdh.setPrivateKey(Buffer.from(VECTOR.clientPrivHex, 'hex'));
    const secret = cliEcdh.computeSecret(Buffer.from(bundle.publicKeyHex, 'hex'));

    const allBytes = Buffer.from(bundle.accessTokenHex, 'hex');
    const tag = allBytes.subarray(allBytes.length - 16);
    const ct = allBytes.subarray(0, allBytes.length - 16);
    const decipher = createDecipheriv('aes-256-gcm', secret, Buffer.from(bundle.nonceHex, 'hex'));
    decipher.setAuthTag(tag);
    const plaintext = Buffer.concat([decipher.update(ct), decipher.final()]).toString('utf8');
    expect(plaintext).toBe(VECTOR.plaintext);
  });
});

describe('encryptForClient — fresh server keypair round-trip', () => {
  it('encrypts with a random server keypair; the bundle decrypts back', () => {
    // Use a known client keypair to play "the CLI" in this test.
    const cliEcdh = createECDH('prime256v1');
    cliEcdh.setPrivateKey(Buffer.from(VECTOR.clientPrivHex, 'hex'));
    const clientPubHex = cliEcdh.getPublicKey().toString('hex');

    const plaintext = 'sbp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
    const bundle = encryptForClient(plaintext, clientPubHex);

    const secret = cliEcdh.computeSecret(Buffer.from(bundle.publicKeyHex, 'hex'));
    const allBytes = Buffer.from(bundle.accessTokenHex, 'hex');
    const tag = allBytes.subarray(allBytes.length - 16);
    const ct = allBytes.subarray(0, allBytes.length - 16);
    const decipher = createDecipheriv('aes-256-gcm', secret, Buffer.from(bundle.nonceHex, 'hex'));
    decipher.setAuthTag(tag);
    expect(Buffer.concat([decipher.update(ct), decipher.final()]).toString('utf8')).toBe(plaintext);
  });
});

describe('generateDeviceCode', () => {
  it('returns 8 lowercase hex characters', () => {
    const code = generateDeviceCode();
    expect(code).toMatch(/^[0-9a-f]{8}$/);
  });

  it('1000 successive calls produce ≥999 distinct codes (statistical sanity)', () => {
    const seen = new Set<string>();
    for (let i = 0; i < 1000; i++) seen.add(generateDeviceCode());
    expect(seen.size).toBeGreaterThanOrEqual(999);
  });
});

describe('validateClientPublicKey', () => {
  it('accepts the known-good vector', () => {
    expect(validateClientPublicKey(VECTOR.clientPubHex)).toEqual({ valid: true });
  });

  it('rejects wrong length', () => {
    expect(validateClientPublicKey('04abcd')).toMatchObject({ valid: false, reason: 'wrong_length' });
  });

  it('rejects compressed-form prefixes (02, 03)', () => {
    const compressed = '02' + VECTOR.clientPubHex.slice(2, 66); // 32 bytes after prefix
    expect(validateClientPublicKey(compressed + '0'.repeat(130 - compressed.length)))
      .toMatchObject({ valid: false });
  });

  it('rejects uppercase hex', () => {
    expect(validateClientPublicKey(VECTOR.clientPubHex.toUpperCase()))
      .toMatchObject({ valid: false, reason: 'wrong_format' });
  });

  it('rejects 04-prefixed-but-not-on-curve hex', () => {
    // Random bytes with 04 prefix — extremely unlikely to land on the curve.
    const bogus = '04' + 'aa'.repeat(64);
    const result = validateClientPublicKey(bogus);
    expect(result.valid).toBe(false);
  });

  it('rejects non-string input', () => {
    // @ts-expect-error testing runtime guard
    expect(validateClientPublicKey(undefined)).toMatchObject({ valid: false, reason: 'not_a_string' });
  });
});
