/**
 * CLI device-code login crypto helpers (feature 011).
 *
 * Wire protocol is dictated by the upstream supabase CLI's
 * apps/cli-go/internal/login/login.go. We must conform byte-for-byte.
 *
 * Key facts (see specs/011-cli-device-login/contracts/cli-wire-protocol.md):
 *   - ECDH on NIST P-256 (prime256v1)
 *   - Public keys: uncompressed SEC1 (65 bytes: 0x04 || X || Y)
 *   - ECDH shared secret used DIRECTLY as 32-byte AES key (no KDF)
 *   - AES-256-GCM with random 12-byte nonce
 *   - **Auth tag (16 bytes) concatenated AFTER ciphertext** before hex-encoding —
 *     matches Go's cipher.NewGCM(...).Seal output, which the CLI's Open call expects.
 *     This is the one footgun: Node's createCipheriv('aes-256-gcm', ...) does NOT
 *     auto-append the tag.
 *
 * No third-party crypto dependencies; uses Node 20 stdlib only.
 */

import { createECDH, createCipheriv, randomBytes } from 'node:crypto';

export type ServerKeypair = { privateKey: Buffer; publicKey: Buffer };
export type EncryptedBundle = {
  accessTokenHex: string;
  publicKeyHex: string;
  nonceHex: string;
};

/** Generate an ephemeral ECDH P-256 server keypair. */
export function generateServerKeypair(): ServerKeypair {
  const ecdh = createECDH('prime256v1');
  ecdh.generateKeys();
  return {
    privateKey: ecdh.getPrivateKey(),
    publicKey: ecdh.getPublicKey(), // uncompressed SEC1, 65 bytes
  };
}

/**
 * Encrypt `plaintext` for a CLI client given the client's hex-encoded
 * uncompressed P-256 public key. Returns hex-encoded server pubkey,
 * nonce, and ciphertext-with-tag for the polling endpoint to return.
 *
 * Implementation MUST match Go's:
 *   cipher.NewGCM(aes.NewCipher(secret)).Seal(nil, nonce, plaintext, nil)
 * which returns ciphertext || authTag concatenated.
 */
export function encryptForClient(plaintext: string, clientPubKeyHex: string): EncryptedBundle {
  const ecdh = createECDH('prime256v1');
  ecdh.generateKeys();
  const serverPub = ecdh.getPublicKey();

  const clientPub = Buffer.from(clientPubKeyHex, 'hex');
  const sharedSecret = ecdh.computeSecret(clientPub); // 32 bytes for P-256

  const nonce = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', sharedSecret, nonce);
  const ct = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag(); // 16 bytes

  // CRITICAL: concat tag AFTER ciphertext to match Go's Seal output format.
  // Without this, the CLI's Open call interprets the wrong bytes as the tag
  // and fails with "cannot decrypt access token".
  const accessTokenHex = Buffer.concat([ct, tag]).toString('hex');

  return {
    accessTokenHex,
    publicKeyHex: serverPub.toString('hex'),
    nonceHex: nonce.toString('hex'),
  };
}

/**
 * Encrypt `plaintext` using a CALLER-PROVIDED server private key. Used only by
 * unit tests that need to verify the byte-exact output against known vectors
 * generated by the upstream Go implementation.
 */
export function encryptForClientWithFixedKey(
  plaintext: string,
  clientPubKeyHex: string,
  serverPrivKeyHex: string,
  nonceHex: string,
): EncryptedBundle {
  const ecdh = createECDH('prime256v1');
  ecdh.setPrivateKey(Buffer.from(serverPrivKeyHex, 'hex'));
  const serverPub = ecdh.getPublicKey();

  const clientPub = Buffer.from(clientPubKeyHex, 'hex');
  const sharedSecret = ecdh.computeSecret(clientPub);

  const nonce = Buffer.from(nonceHex, 'hex');
  const cipher = createCipheriv('aes-256-gcm', sharedSecret, nonce);
  const ct = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  const accessTokenHex = Buffer.concat([ct, tag]).toString('hex');

  return {
    accessTokenHex,
    publicKeyHex: serverPub.toString('hex'),
    nonceHex: nonce.toString('hex'),
  };
}

/** 8 lowercase-hex chars — the verification code the operator pastes into the CLI. */
export function generateDeviceCode(): string {
  return randomBytes(4).toString('hex');
}

export type PublicKeyValidation = { valid: true } | { valid: false; reason: string };

/**
 * Validate a hex-encoded client public key:
 *   - 130 lowercase hex chars
 *   - starts with '04' (uncompressed SEC1 prefix)
 *   - decodes to a point on the P-256 curve (Node's computeSecret throws if not)
 */
export function validateClientPublicKey(hex: string): PublicKeyValidation {
  if (typeof hex !== 'string') return { valid: false, reason: 'not_a_string' };
  if (hex.length !== 130) return { valid: false, reason: 'wrong_length' };
  if (!/^04[0-9a-f]{128}$/.test(hex)) return { valid: false, reason: 'wrong_format' };

  // Curve point check — Node throws if the bytes don't represent a valid point.
  try {
    const ecdh = createECDH('prime256v1');
    ecdh.generateKeys();
    ecdh.computeSecret(Buffer.from(hex, 'hex'));
    return { valid: true };
  } catch (err) {
    return { valid: false, reason: `not_a_valid_point: ${(err as Error).message}` };
  }
}
