-- 0019_backup_seq.sql
--
-- Feature 086 US6 — numeric surrogate id for backups.
--
-- The platform studio (IS_PLATFORM=true) types require a NUMERIC backup id
-- (`BackupsResponse.backups[].id: number`). The native `backups.id` is a uuid
-- (kept as the CLI / `/v1` contract). `seq` is a table-owned identity bigint
-- exposed as the studio-facing id; the platform restore route resolves it back
-- to the uuid, scoped to the project (services/backups-mgmt-service.ts).
--
-- Uses GENERATED BY DEFAULT AS IDENTITY (not a hand-rolled CREATE SEQUENCE
-- OWNED BY): the identity sequence is owned by the table, so it works whether
-- the migration runs as a superuser or the table owner (a CREATE SEQUENCE ...
-- OWNED BY fails with "sequence must have same owner as table" when the
-- migration role differs from the backups-table owner). Postgres backfills
-- existing rows automatically on ADD COLUMN.
--
-- Idempotent + additive (Constitution I): re-running the whole sequence is a no-op.

ALTER TABLE backups ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- Supports the ref-scoped resolve (instance_ref, seq); seq is globally unique anyway.
CREATE UNIQUE INDEX IF NOT EXISTS backups_ref_seq_uniq ON backups (instance_ref, seq);
