-- 0023_observability.sql
--
-- Feature 116 — admin ops console. Two observability tables written by the
-- worker `observer` job and read (only) by the api admin endpoints.
--
-- Idempotent + additive (Constitution I): re-running the whole sequence is a
-- no-op. Identity surrogate via GENERATED BY DEFAULT AS IDENTITY (NOT a
-- hand-rolled CREATE SEQUENCE ... OWNED BY, which fails with "sequence must
-- have same owner as table" because migrate.ts runs as a superuser that is not
-- the app-role table owner).

-- Time-series resource samples (per project + host) for current values + trends.
CREATE TABLE IF NOT EXISTS resource_samples (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captured_at     timestamptz NOT NULL DEFAULT now(),
  scope           text NOT NULL CHECK (scope IN ('host', 'project')),
  ref             text,
  cpu_pct         numeric,
  mem_used_bytes  bigint,
  mem_limit_bytes bigint,
  disk_used_bytes bigint,
  disk_breakdown  jsonb
);
CREATE INDEX IF NOT EXISTS idx_resource_samples_scope_ref_time
  ON resource_samples (scope, ref, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_resource_samples_captured_at
  ON resource_samples (captured_at);

-- Latest-per-container control-plane status + redacted recent log tail.
CREATE TABLE IF NOT EXISTS control_plane_snapshots (
  container   text PRIMARY KEY,
  captured_at timestamptz NOT NULL DEFAULT now(),
  health      text,
  status      text,
  image       text,
  log_tail    text
);
