import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Navigate, Link } from 'react-router-dom';
import { Terminal, Check, Copy, ExternalLink } from 'lucide-react';
import { apexApi } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { Shell } from '@/components/Shell';
import { SettingsLayout } from '@/components/SettingsLayout';
import { PageHeader } from '@/components/PageHeader';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

/**
 * /settings/cli — installation + setup instructions for the supabase CLI
 * against this selfbase deployment. Includes a copy-ready profile TOML
 * pre-filled with the apex domain, plus the `~/.supabase/profile` setup
 * needed so plain `supabase login` works without a `--profile` flag each
 * invocation.
 *
 * Spec follow-up to feature 011.
 */
export function SettingsCliPage(): React.ReactElement {
  const { user } = useAuth();
  const { data: apexStatus } = useQuery({
    queryKey: ['apex'],
    queryFn: () => apexApi.status(),
    enabled: user?.role === 'admin' || user?.role === 'member',
  });

  if (user && user.role !== 'admin' && user.role !== 'member') {
    return <Navigate to="/dashboard" replace />;
  }

  const apex = apexStatus?.apex ?? '<your-apex-domain>';
  const tomlContent = `name          = "selfbase"
api_url       = "https://api.${apex}"
dashboard_url = "https://${apex}/dashboard"
project_host  = "${apex}"`;

  const writeTomlCmd = `mkdir -p ~/.config && cat > ~/.config/selfbase.toml <<'EOF'
${tomlContent}
EOF`;

  const setDefaultCmd = `printf '%s' "$HOME/.config/selfbase.toml" > ~/.supabase/profile`;

  const loginCmd = `supabase login`;

  const verifyCmd = `supabase projects list`;

  const selfbaseFileCmd = `echo '${apex}' > .selfbase`;

  const wrapperSnippet = `# selfbase + supabase wrapper:
#   - .supabase_token at git root → injected as SUPABASE_ACCESS_TOKEN
#   - .selfbase at git root → contains the selfbase apex (e.g. "${apex}");
#     wrapper auto-generates ~/.config/selfbase/<apex>.toml and passes
#     --profile <path> to the CLI on every invocation
#   - both run independently; either can be absent
#   - explicit --profile on the command line is respected (not overridden)
supabase() {
  local real_supabase
  real_supabase="$(whence -p supabase)"
  if [[ -z "$real_supabase" ]]; then
    echo "supabase: command not found" >&2; return 127
  fi

  local git_root search_dir
  git_root="$(git rev-parse --show-toplevel 2>/dev/null)"

  local extra_env=() extra_args=()

  if [[ -n "$git_root" ]]; then
    # .supabase_token discovery
    local token_file token
    search_dir="$(pwd)"
    while [[ "$search_dir" == "$git_root"* ]]; do
      if [[ -f "$search_dir/.supabase_token" ]]; then
        token_file="$search_dir/.supabase_token"; break
      fi
      [[ "$search_dir" == "$git_root" ]] && break
      search_dir="\${search_dir:h}"
    done
    if [[ -n "$token_file" ]]; then
      token="$(<"$token_file")"; token="\${token##[[:space:]]}"; token="\${token%%[[:space:]]}"
      if [[ -n "$token" ]]; then
        local gitignore="$git_root/.gitignore"
        if [[ -f "$gitignore" ]]; then
          grep -qxF '.supabase_token' "$gitignore" || echo '.supabase_token' >> "$gitignore"
        else
          echo '.supabase_token' > "$gitignore"
        fi
        echo "✓ Using project token (\${token_file#$git_root/})" >&2
        extra_env+=("SUPABASE_ACCESS_TOKEN=$token")
      fi
    fi

    # .selfbase discovery
    local selfbase_file apex profile_path
    search_dir="$(pwd)"
    while [[ "$search_dir" == "$git_root"* ]]; do
      if [[ -f "$search_dir/.selfbase" ]]; then
        selfbase_file="$search_dir/.selfbase"; break
      fi
      [[ "$search_dir" == "$git_root" ]] && break
      search_dir="\${search_dir:h}"
    done
    if [[ -n "$selfbase_file" ]]; then
      apex="$(<"$selfbase_file")"; apex="\${apex##[[:space:]]}"; apex="\${apex%%[[:space:]]}"
      if [[ -n "$apex" ]]; then
        profile_path="$HOME/.config/selfbase/\${apex}.toml"
        if [[ ! -f "$profile_path" ]]; then
          mkdir -p "$HOME/.config/selfbase"
          cat > "$profile_path" <<TOML
# Auto-generated by selfbase zsh wrapper on first use against $apex.
name          = "selfbase"
api_url       = "https://api.$apex"
dashboard_url = "https://$apex/dashboard"
project_host  = "$apex"
TOML
          echo "✓ Generated selfbase profile (\${profile_path/#$HOME/~})" >&2
        fi
        # Respect explicit --profile from the operator
        if ! [[ " $* " =~ " --profile " ]]; then
          echo "✓ Using selfbase profile (\${selfbase_file#$git_root/} → \${profile_path/#$HOME/~})" >&2
          extra_args=(--profile "$profile_path")
        fi
      fi
    fi
  fi

  if (( \${#extra_env[@]} )); then
    env "\${extra_env[@]}" "$real_supabase" "\${extra_args[@]}" "$@"
  else
    "$real_supabase" "\${extra_args[@]}" "$@"
  fi
}`;

  return (
    <Shell bare>
      <SettingsLayout>
        <PageHeader
          title="CLI integration"
          subtitle="Connect the upstream supabase CLI to this selfbase deployment."
        />

        <div className="mt-8 flex flex-col gap-10">
          <Section
            number={1}
            title="Install the supabase CLI"
            body={
              <>
                If you haven't yet, install it via your package manager — see{' '}
                <a
                  href="https://supabase.com/docs/guides/cli/getting-started"
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 underline"
                >
                  official install docs
                  <ExternalLink className="size-3" />
                </a>
                . On macOS: <Code inline>brew install supabase/tap/supabase</Code>.
              </>
            }
          />

          <Section
            number={2}
            title="Save the selfbase profile"
            body={
              <>
                The supabase CLI is configured per-deployment via a small TOML profile that tells it
                where this selfbase install lives. Run this once on each machine you'll use the CLI
                from:
              </>
            }
            code={writeTomlCmd}
          />

          <Section
            number={3}
            title="Make it the global default profile"
            body={
              <>
                So every <Code inline>supabase</Code> command uses this deployment automatically (no{' '}
                <Code inline>--profile</Code> flag needed). This is the simplest path if you only
                work against one selfbase deployment; see Section 6 for the per-project alternative
                if you juggle Cloud + selfbase or multiple selfbase deployments.
              </>
            }
            code={setDefaultCmd}
          />

          <Section
            number={4}
            title="Log in"
            body={
              <>
                Run <Code inline>supabase login</Code> — the CLI will open your browser, you'll see
                a short verification code, paste it back into the terminal, and you're done. The CLI
                writes the access token to <Code inline>~/.supabase/access-token</Code>; tokens
                minted this way show up in{' '}
                <Link to="/settings/tokens" className="underline">
                  Access Tokens
                </Link>{' '}
                with a small "cli" badge so you can revoke them later.
              </>
            }
            code={loginCmd}
          />

          <Section
            number={5}
            title="Verify"
            body={<>Smoke-test that the CLI is now talking to this selfbase deployment:</>}
            code={verifyCmd}
            note="Expected output: a table listing the projects on this deployment (not Supabase Cloud's)."
          />

          <Section
            number={6}
            title="Optional: per-project auto-routing"
            body={
              <>
                If you work across multiple deployments (Cloud + selfbase, or several selfbase
                installs), the global default from Section 3 is awkward. Instead, drop a one-line{' '}
                <Code inline>.selfbase</Code> file at your project's git root containing just the
                apex domain. Then paste the zsh wrapper below into <Code inline>~/.zshrc</Code> — it
                walks up to git root looking for <Code inline>.selfbase</Code> and{' '}
                <Code inline>.supabase_token</Code>, auto-generates the per-apex profile under{' '}
                <Code inline>~/.config/selfbase/&lt;apex&gt;.toml</Code>, and passes{' '}
                <Code inline>--profile</Code> to the CLI automatically. The{' '}
                <Code inline>.selfbase</Code> file is safe to commit — teammates pulling the repo
                get the right routing for free.
              </>
            }
            code={selfbaseFileCmd}
          />

          <Section
            number={7}
            title="The zsh wrapper"
            body={
              <>
                Paste this into your <Code inline>~/.zshrc</Code> (replacing any existing{' '}
                <Code inline>supabase()</Code> function); reload with{' '}
                <Code inline>source ~/.zshrc</Code>.
              </>
            }
            code={wrapperSnippet}
            note="On first selfbase invocation, you'll see '✓ Generated selfbase profile (~/.config/selfbase/<apex>.toml)' once. Every subsequent call prints '✓ Using selfbase profile (...)' for visibility."
          />

          <Card className="bg-secondary/20 p-5">
            <h3 className="m-0 mb-2 text-sm font-medium">Switching back to Supabase Cloud</h3>
            <p className="m-0 text-sm text-muted-foreground">
              Either pass <Code inline>--profile supabase</Code> on a one-off command, wipe the
              default with <Code inline>rm ~/.supabase/profile</Code> and re-run{' '}
              <Code inline>supabase login</Code> (with no <Code inline>--profile</Code>), or — if
              you're using the Section-6 wrapper — just <Code inline>cd</Code> out of any directory
              containing a <Code inline>.selfbase</Code> file.
            </p>
          </Card>
        </div>
      </SettingsLayout>
    </Shell>
  );
}

function Section({
  number,
  title,
  body,
  code,
  note,
}: {
  number: number;
  title: string;
  body: React.ReactNode;
  code?: string;
  note?: string;
}): React.ReactElement {
  return (
    <section>
      <h2 className="m-0 mb-2 flex items-center gap-2 text-base font-medium">
        <span className="grid size-6 place-items-center rounded-full bg-secondary text-xs font-medium">
          {number}
        </span>
        {title}
      </h2>
      <div className="ml-8 flex flex-col gap-2">
        <p className="m-0 text-sm text-muted-foreground">{body}</p>
        {code && <CodeBlock content={code} />}
        {note && <p className="m-0 text-xs text-muted-foreground">{note}</p>}
      </div>
    </section>
  );
}

function CodeBlock({ content }: { content: string }): React.ReactElement {
  const [copied, setCopied] = useState(false);
  return (
    <div className="relative">
      <pre className="m-0 overflow-x-auto rounded-md border border-border bg-secondary/40 p-3 pr-12 font-mono text-xs leading-relaxed text-foreground">
        <code>{content}</code>
      </pre>
      <Button
        type="button"
        variant="ghost"
        size="icon-sm"
        className="absolute right-1.5 top-1.5"
        onClick={() => {
          void navigator.clipboard.writeText(content).then(() => {
            setCopied(true);
            window.setTimeout(() => setCopied(false), 1500);
          });
        }}
        aria-label="Copy"
      >
        {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
      </Button>
    </div>
  );
}

function Code({
  children,
  inline,
}: {
  children: React.ReactNode;
  inline?: boolean;
}): React.ReactElement {
  return inline ? (
    <code className="rounded bg-secondary/60 px-1.5 py-0.5 font-mono text-[12px]">{children}</code>
  ) : (
    <code>{children}</code>
  );
}

// Use the icon in the page header so the sidebar icon + page icon match.
void Terminal;
