/**
 * Shared zsh/bash wrapper snippet for selfbase CLI integration.
 * Used in both /settings/cli and the setup wizard Step 4.
 *
 * Updated for the single `.selfbase` file format (feature 024):
 *   token=sbp_xxx
 *   domain=supaviser.dev
 *
 * Replaces the old two-file system (.selfbase for domain + .supabase_token for token).
 */
export function getWrapperSnippet(_apex: string): string {
  return `# selfbase + supabase wrapper:
#   - .selfbase at git root → contains token= and domain= lines
#     wrapper injects SUPABASE_ACCESS_TOKEN and auto-generates
#     ~/.config/selfbase/<domain>.toml, passing --profile on every invocation
#   - explicit --profile on the command line is respected (not overridden)
supabase() {
  local real_supabase
  real_supabase="$(whence -p supabase)"
  if [[ -z "$real_supabase" ]]; then
    echo "supabase: command not found" >&2; return 127
  fi

  local git_root
  git_root="$(git rev-parse --show-toplevel 2>/dev/null)"

  local extra_env=() extra_args=()

  if [[ -n "$git_root" ]]; then
    # .selfbase discovery — single file with token= and domain= lines
    local selfbase_file _sb_token _sb_domain
    local search_dir="$(pwd)"
    while [[ "$search_dir" == "$git_root"* ]]; do
      if [[ -f "$search_dir/.selfbase" ]]; then
        selfbase_file="$search_dir/.selfbase"; break
      fi
      [[ "$search_dir" == "$git_root" ]] && break
      search_dir="\${search_dir:h}"
    done
    if [[ -n "$selfbase_file" ]]; then
      _sb_token="$(grep '^token=' "$selfbase_file" 2>/dev/null | cut -d= -f2-)"
      _sb_domain="$(grep '^domain=' "$selfbase_file" 2>/dev/null | cut -d= -f2-)"
      _sb_token="\${_sb_token##[[:space:]]}"; _sb_token="\${_sb_token%%[[:space:]]}"
      _sb_domain="\${_sb_domain##[[:space:]]}"; _sb_domain="\${_sb_domain%%[[:space:]]}"

      if [[ -n "$_sb_token" ]]; then
        git -C "$git_root" check-ignore -q "$selfbase_file" 2>/dev/null || \\
          echo "⚠ .selfbase contains a token and is not gitignored" >&2
        echo "✓ Using project token (.selfbase)" >&2
        extra_env+=("SUPABASE_ACCESS_TOKEN=$_sb_token")
      fi

      if [[ -n "$_sb_domain" ]]; then
        local profile_path="$HOME/.config/selfbase/\${_sb_domain}.toml"
        if [[ ! -f "$profile_path" ]]; then
          mkdir -p "$HOME/.config/selfbase"
          cat > "$profile_path" <<TOML
# Auto-generated by selfbase zsh wrapper on first use against $_sb_domain.
name          = "selfbase"
api_url       = "https://api.$_sb_domain"
dashboard_url = "https://$_sb_domain/dashboard"
project_host  = "$_sb_domain"
TOML
          echo "✓ Generated selfbase profile (\${profile_path/#$HOME/~})" >&2
        fi
        if ! [[ " $* " =~ " --profile " ]]; then
          echo "✓ Using selfbase profile (.selfbase → \${profile_path/#$HOME/~})" >&2
          extra_args=(--profile "$profile_path")
        fi
      fi
    fi
  fi

  local supabase_rc
  if (( \${#extra_env[@]} )); then
    env "\${extra_env[@]}" "$real_supabase" "\${extra_args[@]}" "$@"
  else
    "$real_supabase" "\${extra_args[@]}" "$@"
  fi
  supabase_rc=$?

  # Post-login cleanup: 'supabase login --profile <path>' writes ~/.supabase/profile
  # as the implicit global default. Offer to clean it up interactively.
  local subcmd arg
  for arg in "$@"; do
    case "$arg" in
      -*) ;;
      *) subcmd="$arg"; break ;;
    esac
  done
  if [[ $supabase_rc -eq 0 && "$subcmd" == "login" && -f "$HOME/.supabase/profile" ]]; then
    echo "" >&2
    echo "⚠ ~/.supabase/profile is set as the global default profile." >&2
    echo "  While that file exists, plain 'supabase login' routes to whatever" >&2
    echo "  profile it points at. Delete it to switch deployments freely." >&2
    if read -q "REPLY?  Delete ~/.supabase/profile now? [y/N] "; then
      echo "" >&2
      rm -f "$HOME/.supabase/profile"
      echo "  ✓ Removed ~/.supabase/profile" >&2
    else
      echo "" >&2
      echo "  Keeping it. 'rm ~/.supabase/profile' when you need to switch." >&2
    fi
  fi

  return $supabase_rc
}`;
}

export function getSelfbaseFileContent(token: string, domain: string): string {
  return `token=${token}\ndomain=${domain}`;
}
